### PR TITLE
Fix end of unexpected json input

### PR DESCRIPTION
**Pull request by nagiesek**
Previously we were erroring out on a failure or internal error. We now return the result properly with the error. Go Formatting Fixes. Enable Nat Test.

### CODE REVIEW

**Comment by nagiesek** [comment]
Rerun Tests

**Comment by nagiesek** [comment]
@madhanrm @dineshgovindasamy @jstarks @jterry75 this will fix the CRI "end of expected json input" error

**Comment by jterry75** [comment]
This is really great @nagiesek! Thank you very much.

**Comment by madhanrm** [comment]
FYI @ashvindeodhar. Can you check if Azure CNI is returning proper error defined in the cni spec ? 

https://github.com/containernetworking/cni/blob/master/SPEC.md

@PatrickLang

**Comment by nagiesek** [comment]
For future and present reference, #66 is going to represent a general failure in CNI and all errors will return as such until I get around to categorizing and organizing the errors that can occur in CNI in some coherent manner.

**Comment by jterry75** [comment]
> For future and present reference, #66 is going to represent a general failure in CNI and all errors will return as such until I get around to categorizing and organizing the errors that can occur in CNI in some coherent manner.

That's fine. We can always improve over time here. This is a big improvement already.

**Pull request merged**
