### PR TITLE
Prevent panics when a network does not have IPAMs or subnets

### PR DESCRIPTION
**Pull request by katiewasnothere**
Signed-off-by: Kathryn Baldauf <kabaldau@microsoft.com>

### CODE REVIEW

**Comment by katiewasnothere** [comment]
@kevpar @dcantah fyi

**Comment by katiewasnothere** [comment]
@nagiesek not sure if you're the right person to ping here, but these are the changes we talked about recently if you could take a look :)

**Review by dcantah — APPROVED** [review]
LGTM

**Comment by nagiesek** [comment]
LGTM

**Pull request merged**
